#!/usr/bin/env Rscript
# scripts/update_dl_stats/update_dl_stats.R
#
# Fetches gVenn download stats from Bioconductor and injects them
# into docs/index.html between the sentinel comments.
#
# Usage (run from repo root):
#   Rscript scripts/update_dl_stats/update_dl_stats.R
#
# Automate with GitHub Actions (see .github/workflows/update-stats.yml)
# or run locally before git push.

# ── Config ────────────────────────────────────────────────────────────────────
PACKAGE     <- "gVenn"
HTML_FILE   <- "docs/index.html"          # relative to repo root
BASE_URL    <- "https://bioconductor.org/packages/stats/bioc"
YEARS       <- (as.integer(format(Sys.Date(), "%Y")) - 1):as.integer(format(Sys.Date(), "%Y"))
# ─────────────────────────────────────────────────────────────────────────────

message("── Fetching Bioconductor stats for ", PACKAGE, " ──")

fetch_year <- function(year) {
    url  <- sprintf("%s/%s/%s_%d_stats.tab", BASE_URL, PACKAGE, PACKAGE, year)
    message("  GET ", url)
    tryCatch({
        con  <- url(url)
        raw  <- readLines(con, warn = FALSE)
        close(con)
        df   <- read.delim(text = paste(raw, collapse = "\n"), stringsAsFactors = FALSE)
        names(df) <- c("Year", "Month", "ips", "downloads")
        df   <- df[df$Month != "all", ]                          # drop totals row
        df   <- df[df$downloads > 0 | df$ips > 0, ]             # drop empty months
        df$year <- year
        df
    }, error = function(e) {
        warning("  Could not fetch ", year, ": ", conditionMessage(e))
        NULL
    })
}

data_list <- lapply(YEARS, fetch_year)
data      <- do.call(rbind, Filter(Negate(is.null), data_list))

if (is.null(data) || nrow(data) == 0) {
    stop("No data fetched — aborting. Check your internet connection.")
}

# Sort chronologically
month_order  <- c("Jan","Feb","Mar","Apr","May","Jun",
                  "Jul","Aug","Sep","Oct","Nov","Dec")
data$sort_key <- data$year * 100 + match(data$Month, month_order)
data          <- data[order(data$sort_key), ]

message("  ", nrow(data), " active months found: ",
        paste(data$Month, data$year, collapse=", "))

# ── Fetch "Data as of" date from Bioconductor stats page ─────────────────────
stats_page_url <- sprintf("%s/%s/", BASE_URL, PACKAGE)
message("  Fetching as-of date from ", stats_page_url)
as_of <- tryCatch({
    con   <- url(stats_page_url)
    lines <- readLines(con, warn = FALSE)
    close(con)
    hit   <- grep("Data as of", lines, value = TRUE)
    if (length(hit) == 0) stop("not found")
    m <- regmatches(hit[1], regexpr("[A-Za-z]+\.?\s+[0-9]+\s+[A-Za-z]+\s+[0-9]{4}", hit[1]))
    m
}, error = function(e) {
    warning("  Could not fetch as-of date: ", conditionMessage(e))
    format(Sys.Date(), "%a. %d %b %Y")   # fallback to today
})
message("  As-of date: ", as_of)

# ── Build the JS RAW array ────────────────────────────────────────────────────
rows <- apply(data, 1, function(r) {
    sprintf('        { year:%s, month:"%s", dl:%s }',
            r["year"], r["Month"], r["downloads"])
})
raw_js <- paste(
    sprintf('        // Auto-generated by update_dl_stats.R — data as of %s', as_of),
    paste(rows, collapse = ",\n"),
    sep = "\n"
)

# ── Inject into HTML ──────────────────────────────────────────────────────────
# The script looks for two sentinel comments in index.html:
#   /* STATS_DATA_START */
#   /* STATS_DATA_END */
# Everything between them is replaced.

html <- readLines(HTML_FILE, warn = FALSE)

start_pat <- "/* STATS_DATA_START */"
end_pat   <- "/* STATS_DATA_END */"

start_idx <- which(grepl(start_pat, html, fixed = TRUE))
end_idx   <- which(grepl(end_pat,   html, fixed = TRUE))

if (length(start_idx) == 0 || length(end_idx) == 0) {
    stop(
        "Sentinel comments not found in ", HTML_FILE, ".\n",
        "Add these two lines inside your <script> block in index.html:\n",
        "  /* STATS_DATA_START */\n",
        "  /* STATS_DATA_END */"
    )
}

new_html <- c(
    html[1:start_idx],          # keep the START sentinel line
    raw_js,
    html[end_idx:length(html)]  # keep the END sentinel line onwards
)

# Update the as-of date shown in the caption
new_html <- gsub(
    'var AS_OF = "[^"]*";',
    sprintf('var AS_OF = "%s";', as_of),
    new_html
)

writeLines(new_html, HTML_FILE)
message("\u2713 Injected ", nrow(data), " rows into ", HTML_FILE)
message("  As-of: ", as_of)
message("  Total downloads: ", sum(data$downloads))