project:
  output-dir: ../../docs

date-modified: last-modified
date-format: "D MMMM YYYY"
language:
  title-block-modified: "Last updated"

format:
  html:
    toc: true
    toc-depth: 2
    toc-location: left
    number-sections: true
    code-fold: false
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#047857"
    theme:
      - journal
      - custom.scss
    embed-resources: true
    fig-width: 7
    fig-height: 5
    fig-align: center
    include-in-header:
      - text: |
            <link rel="icon" type="image/png" href="img/venn_logo.png">
      - text: |
            <script async src="https://www.googletagmanager.com/gtag/js?id=G-4389F94LTN"></script>
      - text: |
           <script>
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-4389F94LTN');
            </script>

execute:
  echo: true
  warning: false
  message: false
